#!/usr/bin/env python3
"""
Professional parking ticket design test.
Tests different layouts and designs for the vertical parking entry ticket.
"""
from escpos.printer import Usb
import traceback
import time
import uuid

p = None
try:
    print("=" * 50)
    print("Parking Ticket Design Test")
    print("=" * 50)
    print("Connecting to printer...")
    p = Usb(0x0fe6, 0x811e)
    print("Printer connected successfully\n")

    # Set encoding for Spanish characters
    try:
        p.charcode("CP850")
    except Exception:
        pass

    # Sample data for testing
    vehicle_plate = "ABC-1234"
    cabin_id = "CABINA-01"
    entry_time = time.strftime("%Y-%m-%d %H:%M:%S")
    ticket_id = str(uuid.uuid4())[:8].upper()
    qr_data = f"PARKING:{ticket_id}:{vehicle_plate}"
    
    # Use 24 characters width for 80mm paper (safe width)
    WIDTH = 24

    print("Design 1: Minimal Professional")
    print("-" * 50)
    
    # Design 1: Minimal Professional
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True, double_height=True)
    p.text("VERTICAL PARKING\n")
    p.set(align="center", bold=True, double_width=False, double_height=False)
    p.text("Sistema de Estacionamiento\n")
    p.set(align="left", bold=False)
    p.text("=" * WIDTH + "\n")
    p.set(align="center", bold=True)
    p.text("TICKET DE INGRESO\n")
    p.set(align="left", bold=False)
    p.text("=" * WIDTH + "\n")
    p.text(f"Vehículo: {vehicle_plate}\n")
    p.text(f"Espacio:  {cabin_id}\n")
    p.text(f"Fecha:    {entry_time}\n")
    p.text(f"Ticket:   {ticket_id}\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="center")
    p.text("Escanea el código QR\n")
    p.text("para retirar tu vehículo\n")
    p.text("\n")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("Conserve este ticket\n")
    p.text("=" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("Design 2: Corporate with Boxes")
    print("-" * 50)
    
    # Design 2: Corporate with Boxes (using ASCII characters)
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True)
    p.text("VERTICAL PARKING\n")
    p.set(align="center", bold=True, double_width=False)
    p.text("Sistema de Estacionamiento\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="left", bold=False)
    p.text("+" + "-" * (WIDTH - 2) + "+\n")
    p.text("| TICKET DE INGRESO" + " " * (WIDTH - 20) + "|\n")
    p.text("+" + "-" * (WIDTH - 2) + "+\n")
    p.text(f"| Vehículo: {vehicle_plate:<{WIDTH-13}} |\n")
    p.text(f"| Espacio:  {cabin_id:<{WIDTH-13}} |\n")
    p.text(f"| Fecha:    {entry_time[:16]:<{WIDTH-13}} |\n")
    p.text(f"| Ticket:   {ticket_id:<{WIDTH-13}} |\n")
    p.text("+" + "-" * (WIDTH - 2) + "+\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="center")
    p.text("CÓDIGO QR\n")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("Escanea para retirar\n")
    p.text("=" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("Design 3: Modern with Separators")
    print("-" * 50)
    
    # Design 3: Modern with Separators (using ASCII)
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True)
    p.text("VERTICAL PARKING\n")
    p.set(align="center", bold=False, double_width=False)
    p.text("-" * WIDTH + "\n")
    p.set(align="center", bold=True)
    p.text("TICKET DE INGRESO\n")
    p.set(align="left", bold=False)
    p.text("-" * WIDTH + "\n")
    p.text("\n")
    p.set(align="left", bold=True)
    p.text("Vehículo:\n")
    p.set(align="left", bold=False)
    p.text(f"  {vehicle_plate}\n")
    p.text("\n")
    p.set(align="left", bold=True)
    p.text("Espacio:\n")
    p.set(align="left", bold=False)
    p.text(f"  {cabin_id}\n")
    p.text("\n")
    p.set(align="left", bold=True)
    p.text("Fecha y Hora:\n")
    p.set(align="left", bold=False)
    p.text(f"  {entry_time}\n")
    p.text("\n")
    p.set(align="left", bold=True)
    p.text("Número de Ticket:\n")
    p.set(align="left", bold=False)
    p.text(f"  {ticket_id}\n")
    p.text("\n")
    p.text("-" * WIDTH + "\n")
    p.set(align="center")
    p.text("\n")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("Escanea el código QR para\n")
    p.text("retirar tu vehículo\n")
    p.text("-" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("Design 4: Compact Professional")
    print("-" * 50)
    
    # Design 4: Compact Professional
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True)
    p.text("VP\n")
    p.set(align="center", bold=True, double_width=False)
    p.text("VERTICAL PARKING\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="left", bold=True)
    p.text("INGRESO\n")
    p.set(align="left", bold=False)
    p.text("-" * WIDTH + "\n")
    p.text(f"Veh: {vehicle_plate} | {cabin_id}\n")
    p.text(f"Fecha: {entry_time[:16]}\n")
    p.text(f"Ticket: {ticket_id}\n")
    p.text("-" * WIDTH + "\n")
    p.set(align="center")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("Escanea para retirar\n")
    p.text("=" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("Design 5: Full Corporate")
    print("-" * 50)
    
    # Design 5: Full Corporate with Instructions
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True, double_height=True)
    p.text("VERTICAL PARKING\n")
    p.set(align="center", bold=True, double_width=False, double_height=False)
    p.text("Sistema de Estacionamiento Vertical\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="center", bold=True)
    p.text("TICKET DE INGRESO\n")
    p.set(align="left", bold=False)
    p.text("=" * WIDTH + "\n")
    p.text("\n")
    p.set(align="left", bold=True)
    p.text("INFORMACIÓN DEL VEHÍCULO\n")
    p.set(align="left", bold=False)
    p.text("-" * WIDTH + "\n")
    p.text(f"Placa:        {vehicle_plate}\n")
    p.text(f"Espacio:      {cabin_id}\n")
    p.text(f"Fecha/Hora:   {entry_time}\n")
    p.text(f"N° Ticket:    {ticket_id}\n")
    p.text("-" * WIDTH + "\n")
    p.text("\n")
    p.set(align="center", bold=True)
    p.text("CÓDIGO DE RETIRO\n")
    p.set(align="center", bold=False)
    p.text("\n")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("-" * WIDTH + "\n")
    p.set(align="center", bold=True)
    p.text("INSTRUCCIONES\n")
    p.set(align="left", bold=False)
    p.text("1. Conserve este ticket\n")
    p.text("2. Escanea el código QR\n")
    p.text("3. Retire su vehículo\n")
    p.text("-" * WIDTH + "\n")
    p.set(align="center", bold=False)
    p.text("Gracias por usar nuestro servicio\n")
    p.text("=" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("Design 6: Bilingual Professional")
    print("-" * 50)
    
    # Design 6: Bilingual Professional
    p.text("\n\n")
    p.set(align="center", bold=True, double_width=True)
    p.text("VERTICAL PARKING\n")
    p.set(align="center", bold=False, double_width=False)
    p.text("Vertical Parking System\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="center", bold=True)
    p.text("ENTRY TICKET / TICKET DE INGRESO\n")
    p.set(align="left", bold=False)
    p.text("=" * WIDTH + "\n")
    p.text(f"Vehicle / Vehículo: {vehicle_plate}\n")
    p.text(f"Space / Espacio:    {cabin_id}\n")
    p.text(f"Date / Fecha:       {entry_time[:10]}\n")
    p.text(f"Time / Hora:        {entry_time[11:19]}\n")
    p.text(f"Ticket #:           {ticket_id}\n")
    p.text("=" * WIDTH + "\n")
    p.set(align="center")
    p.text("Scan QR Code / Escanea QR\n")
    p.text("\n")
    p.qr(qr_data, size=10, ec=3)
    p.text("\n")
    p.set(align="center", bold=False)
    p.text("Keep this ticket / Conserve este ticket\n")
    p.text("=" * WIDTH + "\n")
    p.text("\n\n\n")
    p.cut()

    print("\nAll design tests completed!")
    print("Review the printed tickets and choose your preferred design.")

except Exception as e:
    print(f"Error: {e}")
    traceback.print_exc()
finally:
    if p is not None:
        try:
            p.close()
            print("Printer connection closed.")
        except Exception as close_error:
            print(f"Error closing printer: {close_error}")

